HelmChartPath: ''
RuntimeType: Container
ServiceType: private
ArtifactSourceType: DockerCompose
ServiceBuildRegion: ap-southeast-1
RepoName: LYH-RAIN/FastGPT
DockerComposeEnvPath: .env
RegionId: cn-hangzhou
CustomParameters: ''
DockerComposeYamlPath: deploy/docker/docker-compose-pgvector.yml
Owner: LYH-RAIN
Branch: main
Platform: github
